### ISSUE TITLE
Easy pivoting with Ligolo-ng

### ISSUE THREAD

**Issue by psyray** [ThePorgs/Exegol-resources#4]
Hi,

How about add the excellent tunneling tool **ligolo-ng** ?
https://github.com/nicocha30/ligolo-ng

- It's french, 
- It prevents proxychains use,
- It uses a tun interface instead of socks

![image](https://user-images.githubusercontent.com/1230954/208935946-14515161-b049-4a88-802e-ef3e760ffe9f.png)

## Easy to use
- An agent executable for the victim,
```sh
./agent -connect IP:11601 -ignore-cert & disown
```

- A proxy executable for the attacker,
```sh
ip tuntap add user [your_username] mode tun ligolo
ip link set ligolo up
./proxy -selfcert
```

- We list interface on the victime machine through **Ligolo-ng**
![image](https://user-images.githubusercontent.com/1230954/208934895-a45b4e97-1b2b-4b16-a560-1fb1e65a5af1.png)

- We add the route to the `10.1.1.0/24`

```sh
ip route add 192.168.0.0/24 dev ligolo
```

And, in **ligolo-ng** we could start a tunneled session

```sh
[Agent : root@sean] » start
[Agent : root@sean] » INFO[0786] Starting tunnel to root@sean
```

We now have a complete tun access to the 10.1.1.0/24 network from our machine with all our tooling

And last but not least, it's available for a lot of OS/Arch
![image](https://user-images.githubusercontent.com/1230954/208935362-1c432803-edba-43e5-98cd-0838570dc96b.png)

Como se dice en francés : "L'essayer c'est l'adopter" :grin:

**Comment by QU35T-code** [comment]
#9 https://github.com/ThePorgs/Exegol-images/pull/144
